# Generated by Django 5.2.6 on 2025-09-28 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_usuario_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='activo',
            new_name='estado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Subrecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RolRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.recurso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.rol')),
                ('subrecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.subrecurso')),
            ],
            options={
                'unique_together': {('rol', 'recurso', 'subrecurso')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
