# Generated by Django 5.2.6 on 2025-09-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_recurso_rol_rename_activo_usuario_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('idzona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'ad_zona',
            },
        ),
    ]
