# Generated by Django 5.2.6 on 2025-09-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0004_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('idunidad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.usuario')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.zona')),
            ],
            options={
                'verbose_name': 'Unidad Habitacional',
                'verbose_name_plural': 'Unidades Habitacionales',
                'db_table': 'ad_unidad',
            },
        ),
    ]
