# Generated by Django 5.2.6 on 2025-09-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0005_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('idtipo_documento_identidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'ad_tipo_documento_identidad',
            },
        ),
    ]
