# Generated by Django 5.2.6 on 2025-09-30 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_tipodocumentoidentidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('idresidente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('extension_documento', models.CharField(blank=True, max_length=10, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100, null=True)),
                ('relacion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.tipodocumentoidentidad')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.unidad')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.usuario')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
                'db_table': 'ad_residente',
            },
        ),
    ]
