# Generated by Django 5.2.6 on 2025-09-30 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0007_residente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenteFoto',
            fields=[
                ('idfoto', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.residente')),
            ],
            options={
                'verbose_name': 'Foto de Residente',
                'verbose_name_plural': 'Fotos de Residentes',
                'db_table': 'ad_residente_foto',
            },
        ),
    ]
