# Generated by Django 5.2.6 on 2025-09-30 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0009_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoFoto',
            fields=[
                ('idfoto', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.vehiculo')),
            ],
            options={
                'verbose_name': 'Foto de Vehículo',
                'verbose_name_plural': 'Fotos de Vehículos',
                'db_table': 'ad_vehiculo_foto',
            },
        ),
    ]
