# Generated by Django 5.2.6 on 2025-09-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0010_vehiculofoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('idaviso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.usuario')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'db_table': 'ad_aviso',
            },
        ),
    ]
