# Generated by Django 5.2.6 on 2025-09-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'db_table': 'ad_area_comun',
            },
        ),
    ]
