# Generated by Django 5.2.6 on 2025-09-30 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0012_areacomun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaArea',
            fields=[
                ('idreserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.areacomun')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.unidad')),
                ('usuario_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.usuario')),
            ],
            options={
                'verbose_name': 'Reserva de Área Común',
                'verbose_name_plural': 'Reservas de Áreas Comunes',
                'db_table': 'ad_reserva_area',
            },
        ),
    ]
