# Generated by Django 5.2.6 on 2025-09-30 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0013_reservaarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('idtarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=20)),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.usuario')),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'db_table': 'ad_tarea_mantenimiento',
            },
        ),
    ]
