# Generated by Django 5.2.6 on 2025-09-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0014_tareamantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('idpreventivo', models.AutoField(primary_key=True, serialize=False)),
                ('frecuencia', models.CharField(max_length=20)),
                ('ultima_fecha', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.areacomun')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.usuario')),
            ],
            options={
                'verbose_name': 'Mantenimiento Preventivo',
                'verbose_name_plural': 'Mantenimientos Preventivos',
                'db_table': 'ad_mantenimiento_preventivo',
            },
        ),
    ]
