# Generated by Django 5.2.6 on 2025-10-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0015_mantenimientopreventivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentefoto',
            name='rekognition_face_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
