# Generated by Django 5.2.6 on 2025-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConcepto',
            fields=[
                ('idtipo_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Concepto',
                'verbose_name_plural': 'Tipos de Concepto',
                'db_table': 'cn_tipo_concepto',
            },
        ),
    ]
