# Generated by Django 5.2.6 on 2025-09-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_aviso'),
        ('cn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPrecio',
            fields=[
                ('idconcepto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cn.tipoconcepto')),
                ('usuario_alta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.usuario')),
            ],
            options={
                'verbose_name': 'Concepto con Precio',
                'verbose_name_plural': 'Conceptos con Precio',
                'db_table': 'cn_concepto_precio',
            },
        ),
    ]
