# Generated by Django 5.2.6 on 2025-09-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_aviso'),
        ('cn', '0002_conceptoprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadConcepto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('monto_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cn.conceptoprecio')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.unidad')),
            ],
            options={
                'verbose_name': 'Concepto Asignado a Unidad',
                'verbose_name_plural': 'Conceptos por Unidad',
                'db_table': 'cn_unidad_concepto',
            },
        ),
    ]
