# Generated by Django 5.2.6 on 2025-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0003_unidadconcepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('idformapago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'cn_forma_pago',
            },
        ),
    ]
