# Generated by Django 5.2.6 on 2025-09-30 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0011_aviso'),
        ('cn', '0004_formapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('idcuota', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=7)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_pago', models.CharField(default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cn.conceptoprecio')),
                ('forma_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cn.formapago')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ad.unidad')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'db_table': 'cn_cuota',
            },
        ),
    ]
