# Generated by Django 5.2.6 on 2025-09-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('reference_image', models.ImageField(upload_to='residents/')),
                ('rekognition_face_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
