# Generated by Django 5.2.6 on 2025-09-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_security', '0002_accessevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='unknown_visitors/')),
                ('face_id', models.CharField(max_length=100)),
                ('similarity', models.FloatField()),
            ],
        ),
    ]
