# Generated by Django 5.2.6 on 2025-09-21 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_security', '0003_unknownvisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='vehicle_events/')),
                ('plate_number', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('matched_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_security.resident')),
            ],
        ),
    ]
