# Generated by Django 5.2.6 on 2025-09-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_security', '0004_vehicleaccessevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleaccessevent',
            name='placa_valida',
            field=models.BooleanField(default=False),
        ),
    ]
