# Generated by Django 5.2.6 on 2025-09-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_security', '0006_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSospechoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='eventos_sospechosos/')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('confianza', models.FloatField()),
                ('metadatos', models.JSONField(default=dict)),
            ],
        ),
    ]
