# Generated by Django 5.2.6 on 2025-10-01 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0016_residentefoto_rekognition_face_id'),
        ('ai_security', '0007_eventosospechoso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessevent',
            name='matched_resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ad.residente'),
        ),
    ]
