from .recurso import Recurso
from .rol_recurso import RolRecurso
from .rol import Rol
from .subrecurso import Subrecurso
from .usuario import Usuario
from .usuario_rol import UsuarioRol
from .zona_model import Zona
from .unidad_model import Unidad
from .tipo_documento_model import TipoDocumentoIdentidad
from .residente_model import Residente
from .residente_foto_model import ResidenteFoto
from .vehiculo_model import Vehiculo
from .vehiculo_foto_model import VehiculoFoto
from .aviso_model import Aviso
from .area_comun_model import AreaComun
from .reserva_area_model import ReservaArea
from .tarea_mantenimiento_model import TareaMantenimiento
from .mantenimiento_preventivo_model import MantenimientoPreventivo